model_name: "google/mobilenet_v2_1.0_224"
data_root: "./data/asl_alphabet_dataset/asl_alphabet_preprocessed"
output_dir: "./experiments"
num_train_epochs: 5
batch_size: 32
learning_rate: 3e-4
eval_strategy: "epoch"
logging_steps: 50
save_strategy: "epoch"
seed: 123
