model_name: "WinKawaks/vit-tiny-patch16-224"
data_root: "./data/asl_alphabet_dataset/asl_alphabet_preprocessed"
output_dir: "./experiments"
num_train_epochs: 5
batch_size: 16
learning_rate: 5e-5
eval_strategy: "epoch"
logging_steps: 50
save_strategy: "epoch"
seed: 42
